/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/toilmaster3000/v1/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Approval-history analytics for a selectable range (slice 2: time picker) */
        get: operations["get-analytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/toilmaster3000/v1/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Approval Feed, newest-first */
        get: operations["list-approvals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/toilmaster3000/v1/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Needs-Human-Review queue (derived live) */
        get: operations["list-queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/toilmaster3000/v1/queue/{number}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manual override approve (the only path to approve a breaking change) */
        post: operations["approve-queue-item"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/toilmaster3000/v1/queue/{number}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a queued PR's diff on demand (the Diff card) */
        get: operations["get-queue-diff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/toilmaster3000/v1/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List rules in file order */
        get: operations["list-rules"];
        put?: never;
        /** Create a rule */
        post: operations["create-rule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/toilmaster3000/v1/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Full-replace a rule (also enable/disable) */
        put: operations["update-rule"];
        post?: never;
        /** Delete a rule */
        delete: operations["delete-rule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/toilmaster3000/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the analytics assumption constants (the chip) */
        get: operations["get-settings"];
        /** Full-replace the analytics assumption constants */
        put: operations["update-settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/toilmaster3000/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cycle status line */
        get: operations["get-status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Analytics: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Analytics.json
             */
            readonly $schema?: string;
            assumptions: components["schemas"]["Assumptions"];
            auto_approved: components["schemas"]["Stat"];
            by_type: components["schemas"]["TypeCohortRow"][] | null;
            delta_label: string;
            human_review: components["schemas"]["Stat"];
            /** Format: int64 */
            switches_saved: number;
            switches_saved_delta: components["schemas"]["Delta"];
            /** Format: double */
            switches_saved_money_high: number;
            /** Format: double */
            switches_saved_money_low: number;
            switches_saved_series: number[] | null;
        };
        Approval: {
            /** Format: date-time */
            approved_at: string;
            author: string;
            manual: boolean;
            matched_rule: string;
            /** Format: int64 */
            number: number;
            /** @enum {string} */
            state: "open" | "merged" | "closed" | "unknown";
            title: string;
            title_parts: components["schemas"]["TitleParts"];
            url: string;
        };
        Assumptions: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Assumptions.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description High CHF estimate of one saved context switch (seeded 26: 23-min flow break at loaded cost)
             */
            cost_high: number;
            /**
             * Format: int64
             * @description Low CHF estimate of one saved context switch (seeded 10: ~10-min refocus at gross salary)
             */
            cost_low: number;
            /** @description Symbol prefixed onto the money figure (seeded "CHF") */
            currency: string;
        };
        CycleStatus: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CycleStatus.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            approved_count: number;
            /** Format: int64 */
            dropped_count: number;
            /** Format: date-time */
            last_run: string | null;
            outcome: string;
            /** Format: int64 */
            queue_count: number;
        };
        Delta: {
            /** Format: double */
            pct: number;
            state: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        FileDiff: {
            /** Format: int64 */
            additions: number;
            /** Format: int64 */
            deletions: number;
            filename: string;
            patch: string;
            status: string;
        };
        ManualApproveOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ManualApproveOutputBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            number: number;
            ok: boolean;
        };
        PRDiffBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PRDiffBody.json
             */
            readonly $schema?: string;
            files: components["schemas"]["FileDiff"][] | null;
            /** Format: int64 */
            total_files: number;
        };
        QueueItem: {
            /** Format: int64 */
            additions: number;
            author: string;
            /** Format: int64 */
            changed_files: number;
            /** Format: int64 */
            deletions: number;
            /** Format: int64 */
            number: number;
            reasons: string[] | null;
            title: string;
            title_parts: components["schemas"]["TitleParts"];
            url: string;
        };
        RuleBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/RuleBody.json
             */
            readonly $schema?: string;
            authors_exclude?: string[] | null;
            authors_include?: string[] | null;
            /** @description Rule class: approve (default) or review */
            class?: string;
            description_exclude?: string;
            description_include?: string;
            /**
             * Format: int64
             * @description Upper diff-size bound (additions+deletions); 0 = unconstrained
             */
            diff_max?: number;
            /**
             * Format: int64
             * @description Lower diff-size bound (additions+deletions); 0 = unconstrained
             */
            diff_min?: number;
            /** @description Whether the rule contributes matches */
            enabled?: boolean;
            /** @description Stable generated id (response only) */
            readonly id?: string;
            /** @description Editable rule name */
            name: string;
            scope_exclude?: string;
            scope_include?: string;
            type_exclude?: string;
            type_include?: string;
        };
        Stat: {
            /** Format: int64 */
            count: number;
            delta: components["schemas"]["Delta"];
            series: number[] | null;
            /** Format: double */
            share: number;
        };
        TitleParts: {
            breaking: boolean;
            description: string;
            scopes: string[] | null;
            type: string;
        };
        TypeCohortRow: {
            /** Format: int64 */
            auto: number;
            /** Format: int64 */
            count: number;
            /** Format: int64 */
            human: number;
            /** Format: double */
            share: number;
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-analytics": {
        parameters: {
            query?: {
                /** @description Look-back window: today | week (ISO Monday) | month (calendar 1st) | days (rolling) */
                range?: "today" | "week" | "month" | "days";
                /** @description Rolling-window length in days; required for range=days */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analytics"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueItem"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "approve-queue-item": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description PR number to approve from the queue */
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualApproveOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-queue-diff": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description PR number whose diff to fetch from the queue */
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PRDiffBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleBody"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-rule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-rule": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable rule id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-rule": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable rule id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assumptions"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Assumptions"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assumptions"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CycleStatus"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
